# Generated by Django 3.2.4 on 2021-06-21 22:28

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reader',
            name='first_name',
            field=models.CharField(default='-----', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='reader',
            name='last_name',
            field=models.CharField(default=django.utils.timezone.now, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reader',
            name='phone',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
