# Generated by Django 3.2.4 on 2021-06-21 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_auto_20210621_2228'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reader',
            name='first_name',
            field=models.CharField(default='', max_length=50, null=True),
        ),
    ]
