# Generated by Django 3.2.4 on 2021-06-21 22:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_alter_reader_first_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reader',
            old_name='phone',
            new_name='student_id',
        ),
    ]
