# Generated by Django 3.2.4 on 2021-06-28 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_auto_20210622_2054'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bookstatus',
            options={'ordering': ['due_back'], 'verbose_name_plural': 'Book Statuses'},
        ),
        migrations.AlterField(
            model_name='author',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True, verbose_name='DOB'),
        ),
    ]
